LEDs, Logging & Pins Update
vitosamson/HAB pull request #3
Opened 2019-06-17 19:05 UTC by lanador

- Removed LED code from GPS file
- Logging module updates: added pre-flight check, added logging to .csv
- Updated pins for LEDs and thermistors

2019-06-19 18:09 UTC, vitosamson requested changes
@lanador I left a couple comments which can be taken care of in a future commit, and a couple that should be cleaned up before merging this PR.

2019-06-19 18:09 UTC, vitosamson commented on HAB/HAB.ino
> +const long altitudeCloseThreshold = 55000;
For a future commit: let's move these to the header file as constant definitions.

2019-06-19 18:09 UTC, vitosamson commented on HAB/HAB.ino
> +  if (altitude >= altitudeOpenThreshold && (door1Status == Door::DoorStatus::DOOR_CLOSED || door2Status == Door::DoorStatus::DOOR_CLOSED)){
For a future commit: the `openDoor()` and `closeDoor()` functions check the door status, so we don't need to do that here.

2019-06-19 18:09 UTC, vitosamson commented on HAB/HAB_GPS.ino
> +//      delay(400);
Can we either remove these lines altogether, or add a comment above them explaining that they cause the GPS initialization to fail?

2019-06-19 18:09 UTC, vitosamson commented on HAB/HAB_Logging.h
> +  void setOutdoorBottomTemperature(Sensors::TemperatureData OutdoorBottomTemperature);
Small nitpick: for lines 19 and 20, the variables (`outdoorTopTemperature` and `outdoorBottomTemperature`) should start with a lowercase letter.

2019-06-19 18:09 UTC, vitosamson commented on HAB/HAB_Logging.ino
> +  // Serial.println(firstMissionChar);
Please remove these debug comments.

2019-06-19 18:09 UTC, vitosamson commented on HAB/HAB_Logging.ino
> +      Serial.println("File exists");
Remove debug logging.

2019-06-19 18:09 UTC, vitosamson commented on HAB/HAB_Logging.ino
> + //TODO: rename logMissionData so they are not same
I don't think this comment is relevant anymore?

2019-06-19 18:09 UTC, vitosamson commented on HAB/HAB_Logging.ino
> +  logSystemData("Logging missionData.");
Remove debug logging.

2019-06-19 18:09 UTC, vitosamson commented on HAB/HAB_Logging.ino
> +    Serial.println("Could not open file " + missionLogFileName);
Let's change this to `logSystemData()` instead of `Serial.println()`.

2019-06-19 18:58 UTC, lanador commented on HAB/HAB_GPS.ino
> +//      delay(400);
Sorry about that. I think this is a mistaken commit. This code should have been removed and this commit is from the time when I commented it out.

2019-06-20 15:12 UTC, vitosamson approved these changes
🤘

2019-06-20 15:12 UTC, merged